general:
  project_name: miniresnetv2_ESC10_proj
  logs_dir: logs
  saved_models_dir: saved_models
train_parameters:
  batch_size: 16
  training_epochs: 40
  optimizer: Adam
  initial_learning: 0.001
  patience: 100
  learning_rate_scheduler: reducelronplateau
  restore_best_weights: false
dataset:
  name: custom
  class_names:
  - dog
  - chainsaw
  - crackling_fire
  - helicopter
  - rain
  - crying_baby
  - clock_tick
  - sneezing
  - rooster
  - sea_waves
  audio_path: datasets/ESC-50/audio
  csv_path: datasets/ESC-50/meta/esc50.csv
  file_extension: .wav
  validation_split: 0.1
  test_split: 0.2
  test_path: null
  use_other_class: false
  n_samples_per_other_class: 2
  to_cache: true
pre_processing:
  min_length: 2
  max_length: 10
  target_rate: 16000
  top_db: 60
  frame_length: 3200
  hop_length: 3200
  trim_last_second: false
  lengthen: after
feature_extraction:
  patch_length: 50
  n_mels: 64
  overlap: 0.25
  n_fft: 1024
  hop_length: 320
  window_length: 1024
  window: hann
  center: true
  pad_mode: constant
  power: 2.0
  fmin: 20
  fmax: 7500
  norm: slaney
  htk: false
  to_db: true
  include_last_patch: false
data_augmentation:
  GaussianNoise: 0.5
  VolumeAugment: true
  min_scale: 0.8
  max_scale: 1.2
  SpecAug: false
  freq_mask_param: 1
  time_mask_param: 1
  n_freq_mask: 3
  n_time_mask: 4
  mask_value: 0
model:
  model_type:
    name: miniresnetv2
    n_stacks: 1
    pooling: None
  input_shape:
  - 64
  - 50
  expand_last_dim: true
  transfer_learning: true
  fine_tune: false
  dropout: 0
  multi_label: false
quantization:
  quantize: true
  evaluate: true
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: int8
  quantization_output_type: int8
  export_dir: quantized_models
mlflow:
  uri: ./mlruns
hydra:
  run:
    dir: workspace/miniresnetv2_ESC10_proj_${now:%Y_%m_%d_%H_%M_%S}
